logging:
  pattern:
    # Default at org.springframework.boot.logging.logback.defaults.xml
    # Keywords at https://logback.qos.ch/manual/layouts.html#conversionWord
    console: "%date{ISO8601} %clr(%5p) [%15.15t] %clr(%-40.40logger{39}){cyan} [%mdc] {%kvp} %m%n%wEx"

sentry:
  dsn: # Intentionally left empty, only set in production

spring:
  main:
    banner-mode: off # Don't display large "Spring" text every time the application starts
    keep-alive: true # Virtual threads use are daemons, and JVM exits by default if it has no non-daemon threads
  threads:
    virtual:
      enabled: true # Threads without relying on operating system directly

uishock:
  development: true
